### ISSUE TITLE
Adjustment in icon spacing

### ISSUE THREAD

**Issue by rafatosta** [ubuntu/gnome-shell-extension-appindicator#368]
The space between the icons detract from the system icons.Is it possible to make this adjustment?

![image](https://user-images.githubusercontent.com/18619894/193031425-fa9a96fa-d7e1-4efa-ad87-c5155862e434.png)

If you can't do it, could you signal where I make this adjustment in the code?
I can make a PR with Fix.

Thanks

**Comment by 3v1n0** [comment]
this is handled through the `.panel-status-indicators-box` css class provided by upstream, it could be tuned by using a local `.appindicator-box` css class too, but we does not override it by default.

And that's defined as:
```css
  .panel-status-indicators-box,
  .panel-status-menu-box {
    spacing: 2px;
  }
```
So code is in `appIndicator.js` and `indicatorStatusIcon.js`
